/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.aplicacion.panelUsuario;
import GUI.autos.panelAuto;
import GUI.autos.panelMarca;
import GUI.autos.panelModelo;
import GUI.cliente.panelCliente;
import GUI.tickets.panelFactura;
import GUI.tickets.panelTicket;
import javax.swing.JOptionPane;

/**
 *
 * @author vende
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    
    
    panelCliente pc;
    panelAuto pa;
    panelTicket pt;
    panelFactura pf;
    panelUsuario pu;
    panelMarca pma;
    panelModelo pmo;
    
    String usuario;
    
    public FrmMenuPrincipal() {
        initComponents();
        principal.setLayout(new java.awt.BorderLayout());
        pc = new panelCliente();
        pa = new panelAuto();
        pt = new panelTicket();
        pf = new panelFactura();
        pu = new panelUsuario();
        pma = new panelMarca();
        pmo = new panelModelo();
        principal.add(pc);
        
        apli.setVisible(false);
    }

    public void setUsuario(String u) {
        usuario = u;
        pf.setUsuario(usuario);
        if (usuario.equals("admin") ) {
            apli.setVisible(true);
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        clienteM = new javax.swing.JMenu();
        autoM = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        modelo = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        factura = new javax.swing.JMenuItem();
        apli = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        clienteM.setText("Cliente");
        clienteM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMMouseClicked(evt);
            }
        });
        clienteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMActionPerformed(evt);
            }
        });
        jMenuBar1.add(clienteM);

        autoM.setText("Autos");
        autoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoMActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Auto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        autoM.add(jMenuItem2);

        jMenuItem1.setText("Marca");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        autoM.add(jMenuItem1);

        modelo.setText("Modelo");
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });
        autoM.add(modelo);

        jMenuBar1.add(autoM);

        jMenu8.setText("Servicios");

        jMenuItem4.setText("Tickets");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        factura.setText("Factura");
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        jMenu8.add(factura);

        jMenuBar1.add(jMenu8);

        apli.setText("Aplicación");

        jMenuItem9.setText("Administrar Usuario");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        apli.add(jMenuItem9);

        jMenuBar1.add(apli);

        jMenu10.setText("Salir");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // 0 = cliente, 1 = auto, 2 = tickets, 3 = factura, 4 = usuario
    private void cambiarSeccion( int seccion ) {
        principal.remove(0);
        switch(seccion) {
            case 0 : {
                principal.add(pc);
                break;
            }
            case 1 : {
                principal.add(pa);
                break;
            }
            case 2 : {
                principal.add(pt);
                break;
            }
            case 3 : {
                principal.add(pf);
                break;
            } 
            case 4 : {
                principal.add(pu);
                break;
            }
            case 5 : {
                principal.add(pma);
                break;
            }
            case 6 : {
                principal.add(pmo);
                break;
            }
        }
        
        principal.revalidate();
    }
    
    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu10ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMenu10MouseClicked

    private void autoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoMActionPerformed
        // TODO add your handling code here:
    
       
    }//GEN-LAST:event_autoMActionPerformed

    private void clienteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clienteMActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        cambiarSeccion(1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        cambiarSeccion(2);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        // TODO add your handling code here:
        cambiarSeccion(3);
    }//GEN-LAST:event_facturaActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        cambiarSeccion(4);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void clienteMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMMouseClicked
        // TODO add your handling code here:
        cambiarSeccion(0);
    }//GEN-LAST:event_clienteMMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cambiarSeccion(5);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
        cambiarSeccion(6);
    }//GEN-LAST:event_modeloActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu apli;
    private javax.swing.JMenu autoM;
    private javax.swing.JMenu clienteM;
    private javax.swing.JMenuItem factura;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem modelo;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
