/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.tickets;

import GUI.moduloBuscar;
import conexion.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class panelFactura extends javax.swing.JPanel {

    /**
     * Creates new form panelFactura
     */
    
    moduloBuscar mbf;
    String usuario;
    public panelFactura() {
        initComponents();
         //titulos del buscar
        panelBuscar.setLayout(new java.awt.BorderLayout());
        String [] titulosF = {"NUMEROFAC", "FECHA", "MONTO", "CANCELADO", "MATRICULA", "CLIENTE", "CLIENTEID", "TICKET"};
        //inicializa modulo buscar
        mbf = new moduloBuscar("FacturaFull", titulosF );
        panelBuscar.add(mbf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anular = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setText("FACTURAS");

        jLabel2.setText("<html> Una lista de todas las facturas. <br /> Solo el administrador puede  <br /> anularla. </html>");

        anular.setText("Anular Factura");
        anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularActionPerformed(evt);
            }
        });

        imprimir.setText("Imprimir Factura");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imprimir)
                            .addComponent(anular))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imprimir)
                        .addGap(35, 35, 35)
                        .addComponent(anular)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void setUsuario(String u) {
        usuario = u;
        if ( !(usuario.equals("admin")) ) {
            anular.setEnabled(false);
        }
    }
    
    private void anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularActionPerformed
        // TODO add your handling code here:
        
         
        
        String valores[] = mbf.getValores();
        if (valores[0] == "" ) {
            System.out.println("seleccione algo");
            return;   
        }
        
        int reply = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea anular la factura?\n", "Confirmación", JOptionPane.YES_NO_OPTION);
         if ( reply == JOptionPane.NO_OPTION ) {
                    return;
         }
        
        if  (valores[3] == "Si") {
            JOptionPane.showMessageDialog(null, "Ya esta anulada esa factura!");
        }
        
        
        
        if( Utils.actualizarTabla("factura", "cancelado = 1", "numFac = " + valores[0] ) == 0 ) {
            System.out.println("error");
            return;
        }
        
        mbf.actualizarTabla();
        
    }//GEN-LAST:event_anularActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        // TODO add your handling code here:
        String valores[] = mbf.getValores();
        if (valores[0] == "" ) {
            System.out.println("seleccione algo");
            return;
        }
        imprimirFactura impf = new imprimirFactura();
        impf.imprimir(valores);
        impf.setVisible(true);
    }//GEN-LAST:event_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anular;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelBuscar;
    // End of variables declaration//GEN-END:variables
}
