/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.cliente;

import GUI.clienteRegistrar;
import GUI.cliente.empresaRegistrar;
import GUI.moduloBuscar;
import conexion.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class panelCliente extends javax.swing.JPanel {

    /**
     * Creates new form panelCliente
     */
      personaRegistrar pr;
      empresaRegistrar er;
      moduloBuscar mb;
      
    public panelCliente() {
        initComponents();
        //incializa los paneles
        panelBuscar.setLayout(new java.awt.BorderLayout());
        panelEditar.setLayout(new java.awt.BorderLayout());
        
        
        
        textId.setEnabled(false);
        
        //titulos del buscar
        String [] titulos = {"ID", "NOMBRE", "NUMERO", "TIPO", "EDAD", "CEDULA", "RUC", "CREDITO", "DIRECCION"};
        
        //inicializa modulo buscar
        mb = new moduloBuscar("clienteFull", titulos );
        mb.setVisible(true);
        panelBuscar.add(mb);
        
        //inicializa el panel de inputs
        pr = new personaRegistrar();
        er = new empresaRegistrar();
        panelEditar.add(pr);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEditar = new javax.swing.JPanel();
        panelBuscar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        elim = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        guar = new javax.swing.JButton();
        tipoCliente = new javax.swing.JTextField();
        nuevoC = new javax.swing.JButton();

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setText("Tipo cliente:");

        elim.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        elim.setText("Eliminar Seleccion");
        elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        edit.setText("Editar Seleccion");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        textId.setEditable(false);
        textId.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        guar.setText("Guardar Cambios");
        guar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guarActionPerformed(evt);
            }
        });

        tipoCliente.setEditable(false);
        tipoCliente.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoClienteActionPerformed(evt);
            }
        });

        nuevoC.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        nuevoC.setText("Nuevo Cliente");
        nuevoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guar)))
                .addGap(18, 18, 18)
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nuevoC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(elim)
                .addGap(184, 184, 184)
                .addComponent(edit)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(elim)
                    .addComponent(edit)
                    .addComponent(tipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guar)))
                    .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "¿Está seguro que quiere borrar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if ( reply == JOptionPane.YES_OPTION ) {
            String []valores = mb.getValores();
            //revisa si se realizo el delete bien en cliente
            if (Utils.eliminarTabla("Cliente", "id = " + valores[0]) == 0) {
                System.out.println("elim");
                return;
            };
            
            // revisa a que subtabla va a borrar
            if (valores[3].equals("persona") ) {
                if (Utils.eliminarTabla("Persona", "id = " + valores[0]) == 0 ) {
                    System.out.println("elim");
                }
                pr.limpiarInput();
            }
            else {
                if(Utils.eliminarTabla("Empresa", "id = " + valores[0]) == 0 ) {
                    System.out.println("elim");
                }
                er.limpiarInput();
            }
            tipoCliente.setText("");
            textId.setText("");
            
            mb.actualizarTabla();
            
        }
    }//GEN-LAST:event_elimActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
       
        
        String []valores = mb.getValores();
        
        System.out.println(valores[7]);
       
         if (valores[3].equals("persona") ) {
             pr = new personaRegistrar();
             
             
             
             tipoCliente.setText("persona");
             
             
             
             textId.setText(valores[0]);
             pr.setNombre(valores[1]);
             pr.setTel(valores[2]);
             pr.setEdad(valores[4]);
             pr.setCedula(valores[5]);
             pr.setDir(valores[8]);
         }
         else {
             er = new empresaRegistrar();
             tipoCliente.setText("empresa");
             textId.setText(valores[0]);
             er.setNombre(valores[1]);
             er.setTel(valores[2]);
             er.setDir(valores[8]);
             er.setRuc(valores[6]);
             er.setCredito(valores[7].equals("1"));
             
         }
        
           cambiarInput();
        
    }//GEN-LAST:event_editActionPerformed


    
    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void guarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guarActionPerformed
        
        if (tipoCliente.getText().equals("persona") ){
            // VERIFICA SI SE ESTA EDITANDO UN TEXTO 
            if ( textId.getText().equals("") ) {
                System.out.println("ACAXD");
                return;
            }
            
            if ( !pr.validarInput() ) {
                System.out.println("LO DE LOS INPUTSXD");
            }
            
            String valores = " nombre = '" + pr.getNombre() + "', numero = " + pr.getTel() 
                + ", direccion = '" + pr.getDir() +"'";

            String cond = "id = " + textId.getText();

            Utils.actualizarTabla("cliente", valores, cond);

            valores = " edad = " + pr.getEdad()
                    + ", cedula = '" + pr.getCedula()+"'" ;
            cond = "id = " + textId.getText();

            if (Utils.actualizarTabla("persona", valores, cond) < 0 ) {
                System.out.println("algo no se inserto");
            };
            
            pr.limpiarInput();

            mb.actualizarTabla();
        }
        else {
            // VERIFICA SI SE ESTA EDITANDO UN TEXTO 
            if ( textId.getText().equals("") ) {
                System.out.println("ACAXD");
                return;
            }
            
            if ( !pr.validarInput() ) {
                System.out.println("LO DE LOS INPUTSXD");
            }
            
            String valores = " nombre = '" + er.getNombre() + "', numero = " + er.getTel() 
                + ", direccion = '" + er.getDir() +"'";

            String cond = "id = " + textId.getText();

            Utils.actualizarTabla("cliente", valores, cond);

            valores = " ruc = '" +  er.getRuc()
                    + "', recibeCredito = " + (er.getCredito() ? 1+"" : 0+"" ) ;
            cond = "id = " + textId.getText();

            Utils.actualizarTabla("empresa", valores, cond);
            
            er.limpiarInput();

            mb.actualizarTabla();
            
        }
        
        
    }//GEN-LAST:event_guarActionPerformed

    private void tipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClienteActionPerformed
      
    }//GEN-LAST:event_tipoClienteActionPerformed

    private void nuevoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        registrarNuevoC c = new registrarNuevoC();
        c.setVisible(true);
    }//GEN-LAST:event_nuevoCActionPerformed


    private void cambiarInput() {
        panelEditar.remove(0);
        if( tipoCliente.getText().equals("persona")  ) {
            
            panelEditar.add(pr);
           
        }
        else {
            
            
            panelEditar.add(er);
        }
        panelEditar.revalidate();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JButton elim;
    private javax.swing.JButton guar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nuevoC;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField tipoCliente;
    // End of variables declaration//GEN-END:variables
}
