/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.cliente;

import conexion.Utils;

/**
 *
 * @author User
 */
public class registrarNuevoC extends javax.swing.JFrame {

    /**
     * Creates new form registrarNuevo
     */
    personaRegistrar pr;
    empresaRegistrar er;
    
    public registrarNuevoC(  ) {
        initComponents();
        pr = new personaRegistrar();
        er = new empresaRegistrar();
        principal.setLayout(new java.awt.BorderLayout());
        principal.add(pr);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        guar = new javax.swing.JButton();
        canc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tipoCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        guar.setText("Guardar");
        guar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guarActionPerformed(evt);
            }
        });

        canc.setText("Cancelar");
        canc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setText("Tipo cliente:");

        tipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona", "Empresa" }));
        tipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(canc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guar)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(tipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canc)
                    .addComponent(guar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancActionPerformed

    private void guarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guarActionPerformed
           // TODO add your handling code here:
           
           if ( tipoCliente.getSelectedIndex() == 0 ) {
               if ( !pr.validarInput() ) {
                    System.out.println("LO DE LOS INPUTSXD");
                    return;
                }


                String columnasP[] = {"nombre", "numero", "direccion", "tipo"};
                String valoresP[] = {"'"+pr.getNombre()+"'", pr.getTel() ,"'"+pr.getDir()+"'", "'persona'"};
                int llave = Utils.insertarTabla("cliente", columnasP, valoresP);

                if( llave == 0) {
                    System.out.println("XD error");
                    return;
                }

                String valoresS[] = {pr.getEdad(), "'"+pr.getCedula()+"'", llave+""};
                String columnasS[] = {"edad", "cedula", "id"};

                if ( Utils.insertarTabla("persona", columnasS, valoresS) == 0) {
                    System.out.println("XD error");
                    return;
                }

                this.dispose();
           }
           else {
               
               if ( !er.validarInput() ) {
                    System.out.println("LO DE LOS INPUTSXD");
                    return;
                }


                String columnasP[] = {"nombre", "numero", "direccion", "tipo"};
                String valoresP[] = {"'"+er.getNombre()+"'", er.getTel() ,"'"+er.getDir()+"'", "'empresa'"};
                int llave = Utils.insertarTabla("cliente", columnasP, valoresP);

                if( llave == -1) {
                    System.out.println("XD error");
                    return;
                }

                String valoresS[] = { (er.getCredito() ? 1+"" : 0+"" ), "'"+er.getRuc()+"'", llave+""};
                String columnasS[] = {"recibeCredito", "ruc", "id"};

                if ( Utils.insertarTabla("empresa", columnasS, valoresS) == -1) {
                    System.out.println("XD error");
                    return;
                }

                this.dispose();
               
           }
           
           
    }//GEN-LAST:event_guarActionPerformed

    private void tipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClienteActionPerformed
        // TODO add your handling code here:
        principal.remove(0);
        
        if (tipoCliente.getSelectedIndex() == 0 ) {
            principal.add(pr);
        }
        else {
            principal.add(er);
        }
        principal.revalidate();
        
    }//GEN-LAST:event_tipoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarNuevoC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canc;
    private javax.swing.JButton guar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel principal;
    private javax.swing.JComboBox<String> tipoCliente;
    // End of variables declaration//GEN-END:variables
}
