/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.autos;

import GUI.cliente.*;
import GUI.clienteRegistrar;
import GUI.cliente.empresaRegistrar;
import GUI.moduloBuscar;
import conexion.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class panelModelo extends javax.swing.JPanel {

    /**
     * Creates new form panelCliente
     */
      moduloBuscar mbma;
      moduloBuscar mbmo;
      String marcaId;
      
      boolean modoCrear = false;
      // 0 = auto, 1 == cliente
      int buscarTabla = 0;
      
    public panelModelo() {
        initComponents();
        //incializa los paneles
        panelBuscar.setLayout(new java.awt.BorderLayout());
        
        //titulos del buscar
        String [] titulosM = {"ID", "NOMBRE", "MARCA", "MARCAID"};
        String [] titulosMa= {"ID","NOMBRE"};
        
        //inicializa modulo buscar
        mbma = new moduloBuscar("marca", titulosMa );
        mbmo = new moduloBuscar("modeloFull", titulosM);
        
        
        panelBuscar.add(mbmo);
        
        
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botizq = new javax.swing.JButton();
        botder = new javax.swing.JButton();
        guar = new javax.swing.JButton();
        nuevoA = new javax.swing.JButton();
        modoLabel = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        mar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setText("Modo:");

        botizq.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        botizq.setText("Eliminar Seleccion");
        botizq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botizqActionPerformed(evt);
            }
        });

        botder.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        botder.setText("Editar Seleccion");
        botder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botderActionPerformed(evt);
            }
        });

        guar.setText("Guardar Cambios");
        guar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guarActionPerformed(evt);
            }
        });

        nuevoA.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        nuevoA.setText("Nuevo Modelo");
        nuevoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAActionPerformed(evt);
            }
        });

        modoLabel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        modoLabel.setText("Editar");

        id.setEditable(false);
        id.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        mar.setEditable(false);
        mar.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        mar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marMouseClicked(evt);
            }
        });
        mar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel8.setText("Marca:");

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setText("MODELOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mar)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(nombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(guar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(modoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(88, 88, 88)
                                .addComponent(nuevoA)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botizq)
                .addGap(184, 184, 184)
                .addComponent(botder)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botizq)
                            .addComponent(botder)
                            .addComponent(nuevoA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(modoLabel))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addComponent(guar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int validarInputs() {

        if( nombre.getText().equals("") ) {
            return 0;
        }
        return 1;
    }
    
    private void cambiarModBus( int modo ) {
        
        //Si quita el panel actual
        panelBuscar.remove(0);
        
        // si ya esta el modo buscarCliente, se retorna al regular
        switch ( modo ) {
            case 0 : {
                
                buscarTabla = 0;
                botizq.setText("Eliminar Seleccion");
                botder.setText("Editar Seleccion");

                panelBuscar.add(mbmo);

               mbmo.actualizarTabla();
               break;
            }
               
            
            case 1 : {
                buscarTabla = 1;
                botizq.setText("Cancelar Busqueda");
                botder.setText("Seleccionar Marca");
            
                panelBuscar.add(mbma);
           
                mbma.actualizarTabla();
                break;
            }
        } // de lo contrario se activa
        
        panelBuscar.revalidate();
        
    }
    
    
    private void botizqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botizqActionPerformed
        // Si se busca un cliente en este momento, sera un boton cancelara este modo
        if ( buscarTabla > 0 ) {
            cambiarModBus( 0 );
            
        }
        // De lo contrario, eliminara la seleccion
        else {
            int reply = JOptionPane.showConfirmDialog(null, "¿Está seguro que quiere borrar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if ( reply == JOptionPane.YES_OPTION ) {
                String elim = mbmo.getValores()[0];


                if(Utils.eliminarTabla("modelo", "id = " + elim) == 0) {
                    System.out.println("ELIM");
                }

                limpiar();
                mbmo.actualizarTabla();

            }
            
            
        }
        
    }//GEN-LAST:event_botizqActionPerformed

    private void botderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botderActionPerformed
        // TODO add your handling code here:
        // Si se busca un cliente, se pone en el campo su id
       switch ( buscarTabla ) {
           case 0: {
               
               String valores [] = mbmo.getValores();
               //Si no selecciona nada, no hace nada ex
               if(valores[0] == "") {
                   System.out.println("No hay nada selec");
                   return;
               }
               
               //pone la tabla en modo editar
               modoCrear = false;
               modoLabel.setText("Editar");
               
               //pone la matricula que no se pueda cambiar
               id.setText(valores[0]);
               id.setEnabled(false);
               nombre.setText(valores[1]);
               mar.setText(valores[2]);

               marcaId = valores[3];
               
                 
               break;
           }
           case 1: {
               // Si no selecciona nada, no hace nada xd
               if (mbma.getValores()[0] == "" ) {
                   System.out.println("NO SE PUEDE XD");
               }
               
               String id = mbma.getValores()[1];
               marcaId = mbma.getValores()[0]; 
               mar.setText(id);
           
               cambiarModBus( 0 );
           }
           
       }
        
     
    }//GEN-LAST:event_botderActionPerformed

    private void limpiar() {
        id.setText("");
        nombre.setText("");
        mar.setText("");
    }

    
    private void guarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guarActionPerformed

        if ( validarInputs() == 0 ) {
            System.out.println("Datos incorrectos");
            return;
        }
        //Si se esta craendo un nuevo registro
        if (modoCrear) {
            
           
            String columnas[] = {"nombre", "marcaId"};
            String valores[] = { "'"+ nombre.getText() +"'" ,marcaId};
            
            if(Utils.insertarTabla("modelo", columnas, valores) < 0 ) {
                System.out.println("algo no se inserto");
                return;
            }
            limpiar();
            cambiarModBus(0);
           
        }
        
        //Si se esta editando
        else {
            
            String valores = "marcaId = " + marcaId
                   + ", nombre = '" + nombre.getText() + "'";
           
           String condicion = "id = "+  id.getText() ;
           
           if (Utils.actualizarTabla("modelo", valores, condicion) == 0) {
               System.out.println ("error al update");
               return;
           };
           
           limpiar();
           
           cambiarModBus(0);
            
        }

            
        
        
        
    }//GEN-LAST:event_guarActionPerformed

    private void nuevoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAActionPerformed
        modoCrear = true;
        modoLabel.setText("Crear");
        limpiar();
    }//GEN-LAST:event_nuevoAActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void marKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_marKeyPressed

    private void marMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marMouseClicked
        // TODO add your handling code here:
        cambiarModBus(1);
    }//GEN-LAST:event_marMouseClicked



    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botder;
    private javax.swing.JButton botizq;
    private javax.swing.JButton guar;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mar;
    private javax.swing.JLabel modoLabel;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevoA;
    private javax.swing.JPanel panelBuscar;
    // End of variables declaration//GEN-END:variables
}
